= Introduction to Programming

Introduction to Programming is a book introducing the concepts of programming to non-programmers (using Clojure and Functional Programming style).


== Rationale

Most existing ``Learn Clojure'' and ``Learn Functional Programming'' books target existing programmers and are completely inaccessible to beginners to programming.

Most ``Introduction to Programming'' books teach C-like and/or OOP languages (Ruby, Javascript, etc.), which from my teaching experience, are much harder to learn than Lisps and FP languages.

The journey of many programmers seems


== Approach

The primary goal of this book is to teach a novice how to solve problems with ``programming''.

A Functional Programming approach is taught, but, only insofar as it makes it easier to learn programming (ex. avoiding state, pure functions). The aim is not to be a comprehensive introduction to Functional Programming, hence why Clojure is used, instead of a pure functional language, like, say, Haskell. Also, many ``theoretical'' concepts from FP, such as monads will be skipped.

Clojure is the language used for teaching, because: (1) LISP syntax is very easy to learn for beginners, (2) it is practical (can be used anywhere Java or Javascript are). However, like with FP, this book will only cover Clojure insofar as it is useful for teaching a beginner to program. ``Advanced'' concepts such as macros will be skipped.


== About the Authors

Rafal Dittwald - engineer, developer, programming instructor, entrepreneur


== Setup

`brew install asciidoc`

Then:

`./compile.sh`


== Contributing

PRs welcome!
